# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Sanders
email: ben@sanders.life
description: > # this means to ignore newlines until "baseurl:"
  Ben Sanders is an all-around Geek and loves to write about the latest
  technology/gaming news. If you want a personal take on technology and gaming
  news come have a read. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ben.sanders.life" # the base hostname & protocol for your site
twitter_username: thebensanders
github_username:  bensanders

collections:
  photos:
    output: true
    permalink: /photos/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown
